project_id = "mwxpfjedhceujqmbjasy"

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.upload-to-r2]
verify_jwt = true

[functions.delete-from-r2]
verify_jwt = true
